apiVersion: v1
kind: Service
metadata:
  name: action-server
  namespace: rasa-backend
spec:
  selector:
    app: rasa-actions
  ports:
    - protocol: TCP
      port: 5055  # Assuming the Rasa Actions container uses port 5055
      targetPort: 5055
