apiVersion: v1
kind: Service
metadata:
  name: rasa-load-balancer
  namespace: rasa-backend
spec:
  type: LoadBalancer
  selector:
    app: rasa-open-source
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5005
