apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-open-source
  namespace: rasa-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rasa-open-source
  template:
    metadata:
      labels:
        app: rasa-open-source
    spec:
      containers:
        - name: rasa
          image: namansethi13/rasa-os
          ports:
            - containerPort: 5005
          # securityContext:
          #   runAsUser: 0 
          # command: ["rasa"]
          # args:
          #   - "run"
          #   - "--enable-api"
          #   - "--cors"
          #   - "*"
            # - "--port"
            # - "8000"
      #     volumeMounts:
      #       - name: app-volume
      #         mountPath: /app
      # volumes:
      #   - name: app-volume
      #     hostPath:
      #       path: /C:/Users/namsethi1/learning_rasa/three
